# Generated by Django 3.2 on 2021-04-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientId', models.CharField(help_text='Patient ID is for unique identification.', max_length=128, primary_key=True, serialize=False)),
                ('doctorId', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(help_text='Enter your name', max_length=32)),
                ('age', models.PositiveIntegerField(default=18, help_text='Enter your age')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('address', models.CharField(help_text='Enter your address', max_length=128)),
                ('phone', models.CharField(help_text='Enter your mobile number of 10 digits', max_length=10)),
                ('email', models.EmailField(max_length=32)),
                ('bloodType', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
            ],
        ),
    ]
