# Generated by Django 3.2 on 2021-04-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctorId',
            field=models.CharField(max_length=128),
        ),
    ]
