# Generated by Django 3.2 on 2021-04-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0006_alter_patient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(help_text='Enter your address', max_length=128),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(default=18, help_text='Enter your age'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(help_text='Enter your name', max_length=32),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.PositiveIntegerField(help_text='Enter your mobile number of 10 digits'),
        ),
    ]
