# Generated by Django 3.2 on 2021-04-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_alter_patient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctorId',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
