# Generated by Django 3.2 on 2021-04-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0003_alter_donor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
