# Generated by Django 3.2 on 2021-04-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0004_alter_donor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
