# Generated by Django 3.2 on 2021-04-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0005_alter_donor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donorId',
        ),
    ]
