# Generated by Django 3.2 on 2021-04-25 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0006_remove_donation_donorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donorName',
            field=models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.CASCADE, to='Donor.donor', to_field='name'),
        ),
    ]
