# Generated by Django 3.2 on 2021-04-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0008_alter_donor_bloodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='bloodType',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3),
        ),
    ]
