# Generated by Django 3.2 on 2021-04-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0010_alter_donor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.PositiveIntegerField(help_text='Enter your mobile number'),
        ),
    ]
