# Generated by Django 3.2 on 2021-04-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0013_alter_donor_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'get_latest_by': '-self.date'},
        ),
    ]
