# Generated by Django 3.2 on 2021-04-30 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('bloodType', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, primary_key=True, serialize=False)),
                ('unit', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('requestId', models.AutoField(primary_key=True, serialize=False)),
                ('doctorId', models.CharField(blank=True, max_length=128)),
                ('date', models.DateField(default=datetime.date.today)),
                ('bloodType', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text='Enter the Blood Group required', max_length=3)),
                ('isApproved', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('P', 'Pending')], default='P', max_length=1)),
                ('quantity', models.PositiveIntegerField(help_text='Enter quantity of Blood required')),
                ('patientId', models.ForeignKey(help_text='Patient', on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
