# Generated by Django 3.2 on 2021-04-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='doctorId',
            field=models.CharField(max_length=128),
        ),
    ]
