# Generated by Django 3.2 on 2021-04-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0002_auto_20210501_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='doctorId',
        ),
    ]
