# Generated by Django 3.2 on 2021-05-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0003_remove_bloodrequest_doctorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='btype',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='bloodType',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text='Enter the Blood Group required', max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='BRtype',
        ),
    ]
