# Generated by Django 3.2 on 2021-04-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0003_alter_bloodinventory_bloodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='bloodType',
            field=models.CharField(choices=[('A1', 'A+'), ('A2', 'A-'), ('B1', 'B+'), ('B2', 'B-'), ('O1', 'O+'), ('O2', 'O-'), ('AB1', 'AB+'), ('AB2', 'AB-')], max_length=3),
        ),
    ]
