# Generated by Django 3.2 on 2021-04-25 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_auto_20210426_0158'),
        ('Blood', '0005_auto_20210426_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='bloodType',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text='Enter the Blood Group required', max_length=3),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='patientId',
            field=models.ForeignKey(help_text='Patient', on_delete=django.db.models.deletion.CASCADE, to='Patient.patient'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Enter quantity of Blood required'),
        ),
    ]
