# Generated by Django 3.2 on 2021-04-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blood', '0006_auto_20210426_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodrequest',
            options={'ordering': ['-date']},
        ),
    ]
