# Generated by Django 3.1.7 on 2021-04-10 13:45

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospitalId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('name', models.CharField(help_text='Enter your name', max_length=32)),
                ('age', models.PositiveIntegerField(default=18, help_text='Enter your age')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('address', models.CharField(help_text='Enter your address', max_length=128)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Enter your phone number', max_length=31, unique=True)),
                ('email', models.EmailField(help_text='Enter your email address', max_length=32)),
                ('degree', models.CharField(help_text='Enter your Degree', max_length=32)),
                ('doctorId', models.CharField(help_text='Enter your username', max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='Atleast one each of digit,alphabet,special character required', max_length=32)),
                ('hospitalId', models.ForeignKey(help_text='Enter ID of your hospital', on_delete=django.db.models.deletion.CASCADE, to='Doctor.hospital')),
            ],
        ),
    ]
