# Generated by Django 3.2 on 2021-05-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'permissions': (('is_doctor', 'Has been registered.'), ('is_approved', "Can do the doctor's work"))},
        ),
    ]
