# Generated by Django 3.2 on 2021-04-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'permissions': (('doctor_permission', "Can do the doctor's work"),)},
        ),
    ]
