# Generated by Django 3.1.7 on 2021-04-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_remove_doctor_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctorId',
            new_name='username',
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
