# Generated by Django 3.2 on 2021-04-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_doctor_isapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='isApproved',
            field=models.CharField(choices=[('Y', 'Yes'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
